### ISSUE TITLE
Dependency on lluminate/support: >=4.0.0

### ISSUE THREAD

**Issue by casoetan** [thujohn/share-l4#3]
Can you use a wild card like lluminate/support: >=4.0.\* 
I can't add it to my laravel app because I'm on 4.0.*dev.

Thanks

Wonderful job by the way.

I think some of your other packages have this limitations as well.

**Comment by thujohn** [comment]
Is it ok for you ?

**Comment by casoetan** [comment]
Yes perfect (just had time to try it out). Thanks.
Seems all your packages were updated. Great!!!
